-- =============================================================================
-- BlueCare initial schema — paste into Supabase SQL Editor
-- =============================================================================
-- This bundle creates every public-schema table BlueCare needs through
-- Module 2.B (18 tables + enum types + indexes). Apply this file FIRST,
-- then 0001_rls_policies.sql.
--
-- Idempotent: safe to re-run. Uses `IF NOT EXISTS` for tables and
-- `DROP ... IF EXISTS; CREATE` for types so a partial apply can be retried.
--
-- Generated by hand from db/schema/*.ts on 2026-05-09. When drizzle-kit
-- generate becomes the source of truth (Module 9), this file is replaced
-- by drizzle-kit's output.
-- =============================================================================

-- ---- Enums --------------------------------------------------------------
do $$ begin
  if not exists (select 1 from pg_type where typname = 'role') then
    create type role as enum ('child', 'caregiver', 'therapist', 'admin');
  end if;
  if not exists (select 1 from pg_type where typname = 'locale') then
    create type locale as enum ('en', 'ar');
  end if;
  if not exists (select 1 from pg_type where typname = 'theme') then
    create type theme as enum ('light', 'dark', 'hc');
  end if;
  if not exists (select 1 from pg_type where typname = 'vocabulary_level') then
    create type vocabulary_level as enum ('starter', 'expanding', 'conversational', 'advanced');
  end if;
  if not exists (select 1 from pg_type where typname = 'input_modality') then
    create type input_modality as enum ('symbol', 'speech', 'gesture', 'keyboard');
  end if;
  if not exists (select 1 from pg_type where typname = 'output_modality') then
    create type output_modality as enum ('tts', 'sentence-strip', 'visual-confirmation');
  end if;
  if not exists (select 1 from pg_type where typname = 'symbol_status') then
    create type symbol_status as enum ('active', 'pending_review', 'rejected', 'archived');
  end if;
  if not exists (select 1 from pg_type where typname = 'consent_scope') then
    create type consent_scope as enum (
      'data_processing', 'voice_recording', 'webcam_processing',
      'analytics_dashboard', 'ai_personalization'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'audit_action') then
    create type audit_action as enum (
      'sign_in', 'sign_out', 'profile_create', 'profile_update',
      'child_create', 'child_update', 'child_delete', 'symbol_upload',
      'symbol_moderate', 'session_export', 'consent_grant', 'consent_revoke',
      'data_export', 'data_delete', 'admin_action'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'ai_service') then
    create type ai_service as enum (
      'whisper_stt', 'gpt_personalization', 'elevenlabs_tts', 'azure_tts'
    );
  end if;
end $$;

-- ---- users (mirror of auth.users) ---------------------------------------
create table if not exists public.users (
  id uuid primary key,
  email text not null unique,
  email_confirmed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

-- ---- profiles -----------------------------------------------------------
create table if not exists public.profiles (
  user_id uuid primary key references public.users(id) on delete cascade,
  role role not null,
  full_name text not null,
  preferred_locale locale not null default 'en',
  preferred_theme theme not null default 'light',
  professional_details jsonb,
  caregiver_relationship text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---- children -----------------------------------------------------------
create table if not exists public.children (
  id uuid primary key default gen_random_uuid(),
  caregiver_id uuid not null references public.users(id) on delete cascade,
  full_name text not null,
  preferred_name text,
  date_of_birth date,
  preferred_locale locale not null default 'en',
  preferred_theme theme not null default 'light',
  vocabulary_level vocabulary_level not null default 'starter',
  voice_id text,
  sensory_profile jsonb not null default '{"motion":"full","audio":"full","contrast":"standard","touch":"standard","fontScale":1}'::jsonb,
  ai_suggestion_mode text not null default 'review' check (ai_suggestion_mode in ('auto', 'review')),
  parental_pin_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists children_caregiver_idx on public.children (caregiver_id);

-- ---- symbol_libraries ---------------------------------------------------
create table if not exists public.symbol_libraries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  source text not null check (source in ('arasaac', 'system', 'custom')),
  owner_id uuid,
  attribution text,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---- symbols ------------------------------------------------------------
create table if not exists public.symbols (
  id uuid primary key default gen_random_uuid(),
  library_id uuid not null references public.symbol_libraries(id) on delete cascade,
  label_en text not null,
  label_ar text not null,
  phonetic_en text,
  phonetic_ar text,
  image_path text not null,
  categories jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  global_frequency integer not null default 0,
  status symbol_status not null default 'active',
  submitted_by uuid,
  moderated_by uuid,
  moderated_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists symbols_library_idx on public.symbols (library_id);
create index if not exists symbols_status_idx on public.symbols (status);

-- ---- vocabulary_sets ----------------------------------------------------
create table if not exists public.vocabulary_sets (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,
  symbol_id uuid not null,
  position integer not null,
  category text,
  frequency integer not null default 0,
  last_used_at timestamptz,
  is_favorite integer not null default 0,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists vocab_child_idx on public.vocabulary_sets (child_id);
create index if not exists vocab_child_position_idx on public.vocabulary_sets (child_id, position);
create index if not exists vocab_child_frequency_idx on public.vocabulary_sets (child_id, frequency);

-- ---- sessions -----------------------------------------------------------
create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_seconds integer not null default 0,
  input_count integer not null default 0,
  output_count integer not null default 0,
  successful_selections integer not null default 0,
  therapist_notes text,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists sessions_child_idx on public.sessions (child_id);
create index if not exists sessions_child_started_at_idx on public.sessions (child_id, started_at);

-- ---- input_events -------------------------------------------------------
create table if not exists public.input_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  child_id uuid not null references public.children(id) on delete cascade,
  modality input_modality not null,
  symbol_id uuid,
  latency_ms smallint,
  was_corrected smallint not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  anonymous_event_id text not null
);
create index if not exists input_events_session_idx on public.input_events (session_id);
create index if not exists input_events_child_idx on public.input_events (child_id);
create index if not exists input_events_child_created_idx on public.input_events (child_id, created_at);

-- ---- output_events ------------------------------------------------------
create table if not exists public.output_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  child_id uuid not null references public.children(id) on delete cascade,
  modality output_modality not null,
  payload jsonb not null default '{}'::jsonb,
  duration_ms smallint,
  created_at timestamptz not null default now(),
  anonymous_event_id text not null
);
create index if not exists output_events_session_idx on public.output_events (session_id);
create index if not exists output_events_child_idx on public.output_events (child_id);

-- ---- progress_metrics ---------------------------------------------------
create table if not exists public.progress_metrics (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,
  day date not null,
  active_vocabulary_size integer not null default 0,
  input_count integer not null default 0,
  output_count integer not null default 0,
  avg_sentence_length numeric(5,2) not null default 0,
  success_rate numeric(4,3) not null default 0,
  modality_breakdown jsonb not null default '{"symbol":0,"speech":0,"gesture":0,"keyboard":0}'::jsonb,
  top_symbols jsonb not null default '[]'::jsonb
);
create unique index if not exists progress_metrics_child_day_uniq on public.progress_metrics (child_id, day);
create index if not exists progress_metrics_child_idx on public.progress_metrics (child_id);

-- ---- gamification_state -------------------------------------------------
create table if not exists public.gamification_state (
  child_id uuid primary key references public.children(id) on delete cascade,
  total_stars integer not null default 0,
  current_streak_days integer not null default 0,
  longest_streak_days integer not null default 0,
  stars_awarded_today integer not null default 0,
  stars_awarded_day date,
  unlocked_themes jsonb not null default '[]'::jsonb,
  selected_theme text,
  last_celebration_at timestamptz,
  updated_at timestamptz not null default now()
);

-- ---- audit_log ----------------------------------------------------------
create table if not exists public.audit_log (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.users(id) on delete set null,
  action audit_action not null,
  target_type text,
  target_id text,
  ip_hash text,
  user_agent_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_actor_idx on public.audit_log (actor_id);
create index if not exists audit_action_idx on public.audit_log (action);
create index if not exists audit_created_idx on public.audit_log (created_at);

-- ---- consent_records ----------------------------------------------------
create table if not exists public.consent_records (
  id uuid primary key default gen_random_uuid(),
  granted_by_id uuid not null references public.users(id) on delete restrict,
  subject_child_id uuid references public.children(id) on delete cascade,
  scope consent_scope not null,
  granted boolean not null,
  policy_version text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists consent_granted_by_idx on public.consent_records (granted_by_id);
create index if not exists consent_child_scope_idx on public.consent_records (subject_child_id, scope);
create index if not exists consent_created_idx on public.consent_records (created_at);

-- ---- custom_voices ------------------------------------------------------
create table if not exists public.custom_voices (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,
  recorded_by_id uuid not null references public.users(id) on delete restrict,
  symbol_id uuid not null,
  locale locale not null,
  storage_path text not null,
  duration_ms integer not null,
  size_bytes integer not null,
  label_override text,
  created_at timestamptz not null default now()
);
create index if not exists custom_voices_child_idx on public.custom_voices (child_id);
create index if not exists custom_voices_child_symbol_idx on public.custom_voices (child_id, symbol_id);

-- ---- ai_usage_ledger ----------------------------------------------------
create table if not exists public.ai_usage_ledger (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children(id) on delete cascade,
  service ai_service not null,
  year_month text not null,
  units bigint not null,
  cost_usd numeric(12,6) not null,
  blocked smallint not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists ai_usage_child_month_idx on public.ai_usage_ledger (child_id, year_month);
create index if not exists ai_usage_child_idx on public.ai_usage_ledger (child_id);

-- ---- waitlist_signups (deprecated, retained read-only) ------------------
create table if not exists public.waitlist_signups (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  role text not null default 'family' check (role in ('family', 'therapist', 'school', 'other')),
  locale locale not null default 'en',
  source text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create unique index if not exists waitlist_email_uniq on public.waitlist_signups (email);
create index if not exists waitlist_created_idx on public.waitlist_signups (created_at);
create index if not exists waitlist_role_idx on public.waitlist_signups (role);

-- ---- therapist_invites (Module 2.B) -------------------------------------
create table if not exists public.therapist_invites (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  caregiver_id uuid not null references public.users(id) on delete cascade,
  child_id uuid not null references public.children(id) on delete cascade,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  accepted_by uuid references public.users(id) on delete set null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists therapist_invites_code_uniq on public.therapist_invites (code);
create index if not exists therapist_invites_caregiver_idx on public.therapist_invites (caregiver_id);
create index if not exists therapist_invites_child_idx on public.therapist_invites (child_id);

-- ---- therapist_grants (Module 2.B) --------------------------------------
create table if not exists public.therapist_grants (
  id uuid primary key default gen_random_uuid(),
  caregiver_id uuid not null references public.users(id) on delete cascade,
  therapist_id uuid not null references public.users(id) on delete cascade,
  child_id uuid not null references public.children(id) on delete cascade,
  invite_id uuid references public.therapist_invites(id) on delete set null,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists therapist_grants_pair_uniq on public.therapist_grants (therapist_id, child_id);
create index if not exists therapist_grants_caregiver_idx on public.therapist_grants (caregiver_id);
create index if not exists therapist_grants_therapist_idx on public.therapist_grants (therapist_id);
create index if not exists therapist_grants_child_idx on public.therapist_grants (child_id);

-- ---- draft_onboarding (Module 2.B) --------------------------------------
create table if not exists public.draft_onboarding (
  user_id uuid primary key references public.users(id) on delete cascade,
  step text not null default 'welcome' check (step in (
    'welcome','about_you','about_child','sensory','vocabulary_level',
    'voice','consent','pin','review'
  )),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- =============================================================================
-- Done. Apply 0001_rls_policies.sql next.
-- =============================================================================
