// Conventional commits, with project-specific scopes.
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'test',
        'docs',
        'chore',
        'perf',
        'style',
        'build',
        'ci',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'web',
        'db',
        'shared',
        'auth',
        'i18n',
        'a11y',
        'board',
        'dashboard',
        'admin',
        'marketing',
        'tokens',
        'ai',
        'tts',
        'stt',
        'gestures',
        'gamification',
        'rls',
        'ci',
        'docs',
        'deps',
        'release',
        'config',
      ],
    ],
    'subject-case': [2, 'never', ['upper-case', 'pascal-case', 'start-case']],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [1, 'always', 120],
  },
};
