/**
 * @real-network — hits the LIVE production deploy. Skipped in normal CI.
 *
 * Why: Module 2.A.1.fix postmortem. CI's mock signup path can't catch
 * the kind of drift that broke real signup (Supabase trigger ordering,
 * Vercel env-var misroute, Auth-config redirect-allow-list issues).
 * This spec submits a valid throwaway-email signup against
 * https://bcare-ten.vercel.app/api/auth/signup and asserts 2xx + the
 * documented JSON success shape.
 *
 * Run manually or on a daily cron:
 *   pnpm test:e2e:real
 *
 * Skipped under normal `pnpm test:e2e` because it depends on external
 * network + Supabase + sends a real email.
 */

import { createHash } from 'node:crypto';
import { test, expect } from '@playwright/test';

const LIVE_URL = process.env.PLAYWRIGHT_LIVE_BASE_URL ?? 'https://bcare-ten.vercel.app';
const RUN_REAL = process.env.RUN_REAL_NETWORK_TESTS === '1';

test.describe('real signup against the live deploy [@real-network]', () => {
  test.skip(!RUN_REAL, 'set RUN_REAL_NETWORK_TESTS=1 to run');

  test('POST /api/auth/signup with a throwaway email returns 201 + ok:true', async ({
    request,
  }) => {
    const email = `e2e-real-${Date.now()}@bluecare.test`;
    const textHash = createHash('sha256').update('consent-text-2026-05-09.1').digest('hex');

    const res = await request.post(`${LIVE_URL}/api/auth/signup`, {
      data: {
        method: 'magic-link',
        email,
        fullName: 'E2E Real Probe',
        role: 'family',
        consent: {
          granted: true,
          version: '2026-05-09.1',
          textHash,
        },
        locale: 'en',
      },
      headers: { 'Content-Type': 'application/json' },
    });

    expect(res.status()).toBeGreaterThanOrEqual(200);
    expect(res.status()).toBeLessThan(300);

    const body = (await res.json()) as { ok?: boolean; mode?: string; method?: string };
    expect(body.ok).toBe(true);
    expect(body.mode).toBe('real'); // proves Vercel env vars route to real Supabase
    expect(body.method).toBe('magic-link');
  });

  test('GET /api/health/auth returns ok:true with the expected supabaseProject ref + magic-link URL ok', async ({
    request,
  }) => {
    const res = await request.get(`${LIVE_URL}/api/health/auth`);
    expect(res.ok()).toBeTruthy();
    const body = (await res.json()) as {
      ok?: boolean;
      supabaseProject?: string;
      magicLinkOk?: boolean;
    };
    expect(body.ok).toBe(true);
    // Production should always be the BlueCare project. If this ref ever
    // changes silently (project-ref drift), this assertion fails loudly.
    expect(body.supabaseProject).toBe('ikaaxfhenfbpfjqboixk');
    // Module 2.A.1.fix.2 — the magic-link generated by the admin API
    // must have its action_link point at /auth/callback (no locale prefix).
    expect(body.magicLinkOk).toBe(true);
  });
});
