/**
 * Supabase Database type. Generated by `supabase gen types typescript` against
 * the project's actual schema once the first migration is applied (Module 2).
 *
 * For now the type is a permissive placeholder so client code compiles. The
 * generation step is documented in `docs/deploy.md` and added to CI in
 * Module 9 hardening.
 */
export type Database = {
  public: {
    Tables: Record<string, { Row: Record<string, unknown> }>;
    Views: Record<string, { Row: Record<string, unknown> }>;
    Functions: Record<string, unknown>;
    Enums: Record<string, string>;
  };
};
